### ISSUE TITLE
[Task] Create ResourceIdProposal for substrate

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/webb-rs#51]
## Overview
Add `ResourceIdProposal` proposal for substrate similar to solidity [here](URL). This proposal is used to add `ResourceId` to the Anchor.

## Flow:
-  Propose`ResourceIdProposal`  to the chain using `force_submit_unsigned_proposals`, It gets voted and DKG signs it.
- We will take this signature and call  on `signature-bridge-pallet` `set_resource_id_with_signature` method. This method will validate the proposal add `ResourceId` to the bridge and dispatch a call to the handler.

## Task checklist
- [ ] Implement ResourceIdProposal for substrate
- [ ] Add tests

**Comment by shekohex** [comment]
Hey, could you also mention which pallet/xt and where this will be used?
