### ISSUE TITLE
[DISCUSSION] How to update `TargetSystem` for `cosmwasm`

### ISSUE THREAD

**Issue by duguorong009** [webb-tools/webb-rs#55]
While developing [cosmwasm-proposals](https://github.com/webb-tools/webb-rs/tree/guorong/add-cosmwasm-proposals), @duguorong009 added the proposals.
https://github.com/webb-tools/webb-rs/tree/guorong/add-cosmwasm-proposals/proposals/src/proposal/cosmwasm

Current `cosmwasm-proposal` is a clone of `evm` proposals, since they are much similar(both are handling the group of contracts). 
But, the `evm` proposals cannot be directly used for `cosmwasm` proposals because of one issue arising from the difference between `cosmwasm(cosmos-sdk)` chains & `evm` chains.

The issue is - how to handle the `cosmwasm` chain contract address properly so that it can fit the current `TargetSystem`.
Current `TargetSystem` is designed & implemented for `evm` proposals. (https://docs.rs/webb-proposals/latest/webb_proposals/)
In detail, the `TargetSystem` handles all the contract address as `20 bytes` u8 array since `evm` chains represent the contract & wallet addresses with `20 bytes` u8 array.

But, the `cosmwasm(cosmos-sdk)` chains make use of `keys & addresses` system, different from `evm` chains.
Simply, the contract address in `cosmos-sdk` chains is represented as 63 ~ 65 bytes (chain_prefix + 58 bytes) u8 array.
In depth, `cosmos-sdk` chains use the `address`(20 bytes) derived from `pubkey`(33 bytes), in order to represent account.
But, this `address` is converted to the `accAddress`(human readable account address) by using `bech32` formatting scheme. (Ref: https://docs.cosmos.network/master/basics/accounts.html#keys-accounts-addresses-and-signatures)
In wallet & block explorers, the users/developers use this human-readable address.

So, in the `cosmwasm` proposals, we should handle this difference since the target contract like `anchor` & `vanchor` has the 63 ~ 65 bytes address.

Example: 
Let us assume that `anchor` contract is deployed on `cosmwasm` chains like `juno` & `terra2.0`.
`juno` contract address: `juno1gjg0m75mnav5xftgwjxded5v0shlsj3vk8uh4adk9k7a33034wmssyfupc`(63 bytes)
`terra` contract address: `terra1t3efm9w2289fm4jw8tqmyge8gll56hz5yflaj0yn2ns8hqmn74qqhcjmjm`(64 bytes)
 
 In `evm` chains,
 `Ethereum` chain contract address: `0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE`(40 hex chars-> 20 bytes)

How can we address this difference in `cosmwasm` proposals, especially `TargetSystem`?

**Comment by shekohex** [comment]
Can we do the same as we did with ResourceId? as in we can take the `keccak256(address)` and then take the last 20 bytes? this is one option, the other one is to have a new variant of the `TargetSystem` like `CosmosContract` or something, but the only thing here is the size of the proposal will just get very large and not compatible with other system (esp. the EVM).

in general, I would go with hashing and we treat them as like normal EVM contract addresses.
On the other hand, relayer configuration does not have to force the user to add the hashed addresses, they can in the original form and internally the relayer will hash and use them, the same way we will do it here in webb-rs.

> Would be good, in the `coswasm` module to also include a utils module where you add a function to convert cosmos address to a target system/[u8; 20] address.

**Comment by drewstone** [comment]
We should be storing the most compressed format of data possible, especially if it fits into our already defined structures. For example, if a Bech32 address is longer than its HEX representation, then we choose its HEX representation, not the Bech32 @duguorong009.

**Comment by drewstone** [comment]
An interesting part here about contract addresses is that they store their chain ID as well. That means we could consider using up both the TargetSystem and ChainType + ID to fill the address, since it would contextualize both values. 

@duguorong009 can you provide a more thorough spec of the different options we can choose from here? Currently this post is not very thoroughly described.

**Comment by duguorong009** [comment]
Possible solution from @shekohex 's tips:
As in the `resource_id` generation(https://github.com/webb-tools/webb-rs/issues/55#issue-1281880834), we go for `hashing(keccak256) the contract address & take last 20 bytes from hash(32 bytes)` approach.
From the current `TargetSystem`, I think it is better to keep the `20 bytes` space for contract address.
Surely, this solution needs another mapping of `address_id(20 bytes) => address` in some cosmwasm contracts.
Also, it needs the utility to convert the normal contract address to `address_id(20 bytes)`.
But, it is the solution to keep the current system & does not add extra specific proposals for `cosmwasm` chains.
